### Solicitar restablecimiento de contraseña
POST http://localhost:3007/api/user/forgot-password
Content-Type: application/json

{
  "email": "sebastiangandiagutierrez@gmail.com"
}

### Restablecer contraseña
POST http://localhost:3007/api/user/reset-password
Content-Type: application/json

{
  "userId": "<ID_DEL_USUARIO>",
  "token": "<TOKEN_DEL_EMAIL>",
  "newPassword": "nuevaContraseña123"
}
