### Crear curso de ejemplo
### Crear curso de ejemplo con varias categorías
POST http://localhost:3007/api/courses
Content-Type: application/json

{
  "title": "Sistemas de Big Data",
  "image": "https://res.cloudinary.com/dgbmy60sc/image/upload/v1768986200/939862_czz3ns.jpg",
  "description": "Curso introductorio a los sistemas de Big Data y su aplicación en la industria.",
  "duration": "20 horas",
  "category": ["Tecnología", "Big Data"]
}

### Obtener todos los cursos
GET http://localhost:3007/api/courses
